### PR TITLE
Optionally disable expiration validation

### PR DESCRIPTION
**Pull request by pawelniewie**
to make development easier - you can now use stale data to test out webhooks, etc.

### CODE REVIEW

**Comment by bulinutza** [comment]
@pawelniewie Wouldn't it make more sense to add this as a configurable option in the gem that you can then pass from an initializer in your app? eg. `AtlassianJwtAuthentication.options[:verify_jwt_expiry] = false`

**Comment by pawelniewie** [comment]
It would make more sense but I was lazy ;-) I could refactor this code but I'd like to talk with you about future of this gem before. As I haven't heard from you in a while I did some other changes at my fork and was planning to do more.

For example I introduced Rack middleware that can be used to verify JWT in Sinatra or message_bus which I'm using. I refactored some code for this. I also added user impersonification (which is tied to Rails). You can see changes there https://github.com/MeisterLabs/atlassian-jwt-authentication/compare/master...pawelniewie:master

I want to drop HTTParty module as I moved to Faraday and was planning on moving Faraday stuff into the gem, plus adding Jira REST API client which is currently living inside of our product (and doesn't have to be that way).

Also as you're probably aware Atlassian is introducing some breaking changes due to GDPR - for example JWT token will include user's account id only (no other details) so that needs to be incorporated too. I was planning on working on that later (March 2019 is the deadline).

So I'm curious what are your plans for this gem? Are you also going to work on GDPR changes? Are you still using the gem? If you're not actively developing it/using it I think I'm going part ways but if you do we can discuss how our both needs can be incorporated into one gem.

**Comment by bulinutza** [comment]
Hey Pawel,

I definitely plan to add the GDPR changes, as our products directly depend on this gem. However, the other use cases that you mention don't directly affect us and I wouldn't invest the effort myself to add them. However, I would be happy if you worked on them and contributed directly to this gem, I think overall we can produce a better gem if we work on the same codebase and check each other's code instead of splitting into 2 gems. Would you like to work together on the gem? You can also contact me directly via email on laura[at]meisterlabs[dot]com if you want to move the conversation there.

**Comment by pawelniewie** [comment]
OK, updated the PR with your suggestions.

**Review by bulinutza — APPROVED** [review]

**Pull request merged**
